// Produktdata — Automasjon & Sikkerhet AS
// Rediger denne fila for å legge til, fjerne eller endre produkter.
// img: sti til bilde i images/ (tom streng = typografisk kort med produktkoden).

window.AS_CATEGORIES = ["Alle", "Sikkerhetsstyring", "Sensorer og optikk", "Nødstopp og betjening", "Fysisk sikring", "Tilbehør", "Andre fabrikater"];

window.AS_PRODUCTS = [
  { name: "ABB Jokab Safety", code: "JOKAB", img: "images/jokab.jpg", brand: "ABB", cat: "Sikkerhetsstyring",
    href: "https://new.abb.com/low-voltage/products/safety-products",
    desc: "Hele porteføljen for maskinsikkerhet: styring, sensorer, nødstopp, sikring og tilbehør.",
    doc: "Katalog", docHref: "https://search-ext.abb.com/library/Download.aspx?DocumentID=2TLC010001C0202&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "PLUTO sikkerhets-PLS", code: "PLUTO", img: "images/pluto.png", brand: "ABB", cat: "Sikkerhetsstyring",
    href: "https://new.abb.com/low-voltage/products/safety-products/programmable-safety-controllers",
    desc: "Programmerbar sikkerhetskontroller med ferdige funksjonsblokker og kommunikasjon mellom PLUTO-enheter." },
  { name: "VITAL sikkerhetskontroller", code: "VITAL", img: "images/vital.jpg", brand: "ABB", cat: "Sikkerhetsstyring",
    href: "https://new.abb.com/low-voltage/products/safety-products/vital",
    desc: "Erstatter flere sikkerhetsreleer. Opptil 30 sikkerhetsenheter på én Vital — enkle og tidsbesparende koblinger." },
  { name: "SENTRY sikkerhetsreleer", code: "SENTRY", img: "images/sentry.jpg", brand: "ABB", cat: "Sikkerhetsstyring",
    href: "https://new.abb.com/low-voltage/products/safety-products/safety-relays",
    desc: "BSR for mindre systemer, SSR for spesifikke funksjoner som OSSD, TSR med timer opptil 999 s og universelle USR.",
    doc: "Brosjyre", docHref: "https://search-ext.abb.com/library/Download.aspx?DocumentID=2TLC010037L0201&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "EDEN, MAGNE, MKEY og GKEY", code: "EDEN", img: "images/eden.jpg", brand: "ABB", cat: "Sensorer og optikk",
    href: "https://new.abb.com/low-voltage/products/safety-products/safety-sensors-switches-and-locks",
    desc: "Kontaktfri sensor, magnetlås, prosesslås og sikkerhetslås for overvåkning og sikring av dører og luker." },
  { name: "ORION lysbom og lysgitter", code: "ORION", img: "images/orion.jpg", brand: "ABB", cat: "Sensorer og optikk",
    href: "https://new.abb.com/low-voltage/products/safety-products/optical-safety-devices",
    desc: "Optiske sikkerhetsenheter som oppdager personer og hindringer. Mange lengder, med muting og reset innebygd.",
    doc: "Brosjyre", docHref: "https://search.abb.com/library/Download.aspx?DocumentID=2TLC172062L0201&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "Klemlister, bumpere og matter", code: "KLEMLIST", img: "images/klemlist.png", brand: "ABB", cat: "Sensorer og optikk",
    href: "https://new.abb.com/low-voltage/products/safety-products/safety-contact-edges-bumpers-and-mats",
    desc: "Trykkfølsom sikring i standardutførelser eller skreddersydd etter kundens mål.",
    doc: "Brosjyre", docHref: "https://search-ext.abb.com/library/Download.aspx?DocumentID=2TLC010058L0201&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "SMILE, INCA og LINESTRONG", code: "SMILE", img: "images/smile.png", brand: "ABB", cat: "Nødstopp og betjening",
    href: "https://new.abb.com/low-voltage/products/safety-products/emergency-stops-and-pilot-devices",
    desc: "Kompakt nødstopp, innfelt nødstopp og wirebryter — nødstoppenheter for alle typer installasjon." },
  { name: "Sikre betjeningsenheter", code: "BETJENING", img: "images/betjening.jpg", brand: "ABB", cat: "Nødstopp og betjening",
    href: "https://new.abb.com/low-voltage/products/safety-products/safety-control-devices",
    desc: "Sikker start og stopp av maskiner som betraktes som farlige — tohåndsbetjening, hold-to-run og reset." },
  { name: "QUICK-GUARD grindsystem", code: "QUICK-GUARD", img: "images/quick-guard.jpg", brand: "Troax", cat: "Fysisk sikring",
    href: "https://www.troax.com/no/en/quick-guard",
    desc: "Fleksibelt aluminiumsgrindsystem, lett å tilpasse. Ferdige braketter for dørdetektorer, lysgitter og annet ABB-utstyr." },
  { name: "ABB pilot devices", code: "PILOT", img: "images/pilot.jpg", brand: "ABB", cat: "Tilbehør",
    href: "https://new.abb.com/low-voltage/products/pilot-devices",
    desc: "Knapper og betjeninger av alle typer, med og uten belysning. Tåler mange operasjoner og høy strøm.",
    doc: "Katalog", docHref: "https://search-ext.abb.com/library/Download.aspx?DocumentID=1SFC151007C02__&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "AFS sikkerhetskontaktorer", code: "AFS", img: "images/afs.jpg", brand: "ABB", cat: "Tilbehør",
    href: "https://new.abb.com/low-voltage/products/motor-protection/contactors-for-safety-applications",
    desc: "Kontaktorfamilie designet etter EN ISO 13849 og EN 62061 med integrerte sikkerhetsfunksjoner, for effekter opp til 45 kW.",
    doc: "Brosjyre", docHref: "https://search.abb.com/library/Download.aspx?DocumentID=1SBC100206B02__&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "HF kompakte startere", code: "HF", img: "images/hf.jpg", brand: "ABB", cat: "Tilbehør",
    href: "https://new.abb.com/low-voltage/products/motor-controllers/electronic-compact-starters",
    desc: "Forover/bakover, motorbeskyttelse og nødstopp i én DIN-montert enhet. Opp til 3 kW, 400 VAC, 9 A resistiv last.",
    doc: "Brosjyre", docHref: "https://search.abb.com/library/Download.aspx?DocumentID=2CDC130004B02__%20(PDF)&LanguageCode=en&DocumentPartId=&Action=Launch" },
  { name: "Tilbehør og tilpasningsutstyr", code: "TILBEHØR", img: "images/tilbehor.png", brand: "ABB", cat: "Tilbehør",
    href: "https://new.abb.com/low-voltage/products/safety-products/accessories",
    desc: "Kabler, kontakter, braketter og ekstrautstyr for sikkerhetsproduktene fra ABB Jokab." },
  { name: "Inxpect sikkerhetsradar", code: "RADAR", img: "", brand: "Inxpect", cat: "Andre fabrikater",
    href: "https://www.inxpect.com/en/",
    desc: "Eneste radar sertifisert for maskinsikkerhet. Overvåker farlige områder med kroppsdeteksjon og beskyttelse." },
  { name: "Nordic Door rulleporter", code: "PORT", img: "images/port.jpg", brand: "Nordic Door", cat: "Fysisk sikring",
    href: "https://www.nordicdoor.se/",
    desc: "Rulleporter for maskinsikkerhet: låst i rammen, kontaktfri bryter integrert og kompakt design der lysgitter krever for stor sikkerhetsavstand." },
  { name: "SE2L laserscanner", code: "SE2L", img: "images/se2l.jpg", brand: "IDEC", cat: "Sensorer og optikk",
    href: "https://automasjonsikkerhet.no/kontakt-oss/",
    desc: "Kompakt laserscanner med 20 m deteksjon og 5 m sikkerhetssone. Master/slave uten ekstra kontroller, delbart deteksjonsområde.",
    doc: "Mer informasjon", docHref: "https://automasjonsikkerhet.no/kontakt-oss/" }
];
